### ISSUE TITLE
JS error in api page

### ISSUE THREAD

**Issue by valituguran** [RafalPydyniak/Swaggy-example#2]
I configured swaggy for a Grails hello world project with 1 controller just to see it works.
The resources seem ok but in the main page there is a javascript error (see attached) and nothing is loaded.

| Grails Version: 3.3.11
| JVM Version: 1.8.0_202

build.gradle dependencies:
...
compile 'com.wordnik:swagger-annotations:1.3.8'
compile "org.grails.plugins:swaggydoc-grails3:0.28.0"
...

BookController config:
@Api(value = 'demo')
class BookController { ...

UrlMappings:
...
"/book/"(controller: "book", action: "index")
...

![swaggy err](https://user-images.githubusercontent.com/17927827/78394405-e6502d80-75eb-11ea-8081-8e36b5736391.png)

**Comment by RafalPydyniak** [comment]
Hello, unfortunately I'm not an active Grails developer and because of that I can't really help. I haven't had any experience with grails for more than 3 years now.
I think your best option is to create a new topic on stackoverflow and I'm sure that someone will be able to help you there :)
